configured_endpoints: 35
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-5555f2138d80050120f6177ced10fbadef1eb3cc0fa976e1d8263a3dca9628e9.yml
