configured_endpoints: 23
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-2adc67c56fe2978946e5e562d24d5f50795d7f34a5e838f9e9049d159bc4f59d.yml
