configured_endpoints: 35
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-c1a15dcfbb0e2542c9db1e74f69ebdb2f2fcd06221a20943e674349bfba73f50.yml
