configured_endpoints: 25
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dodo-payments%2Fdodo-payments-325a878d9d47bb229e9e9b900499bf1f0ed3045d1a5bb573940192d51ca3cd79.yml
